### ISSUE TITLE
Contributors

### ISSUE THREAD

**Issue by pleahmacaka** [Techest/SkillX#2]

**Comment by PleahMaCaka** [comment]
@all-contributors please add @PleahMaCaka Core

**Comment by pleahmacaka** [comment]
@all-contributors please add @PleahMaCaka for maintenance

**Comment by PleahMaCaka** [comment]
https://github.com/all-contributors please add @DwarfAmil for maintenance

**Comment by pleahmacaka** [comment]
@all-contributors please add @DwarfAmil for maintenance
